#DB template definition
Description: >
  Master ECS Full MySQL DB template def


Parameters:
  VpcId:
    Type: String

  Subnets:
    Type: CommaDelimitedList
    Description: List of VPC's Subnets Id separeted by Comma

  SourceSecurityGroup:
    Type: String
    Description: Loadbalancer's output Security Group

  DBPORT:
    Type: Number
    Default: 3306

  DBUSER:
    Type: String

  DBPASSWORD:
    Type: String
    NoEcho: true

  DBDATABASE:
    Type: String

  VpcDefaultSG:
    Type: String
    Description: VPC default Security Group

  Environment:
    Type: String

  AppOwner:
    Type: String

  Name:
    Type: String


Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
        Ref: "Subnets"

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: !Sub ${Name} - RDS
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: !Ref DBPORT
        ToPort: !Ref DBPORT
        SourceSecurityGroupId: !Ref SourceSecurityGroup
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref AppOwner

  DBServer:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 50
      DBName: !Ref Name
      DBInstanceIdentifier: !Ref Name
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: 5.6.37
      MasterUsername: !Ref DBUSER
      MasterUserPassword: !Ref DBPASSWORD
      MultiAZ: true
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: 
      - !GetAtt DBSecurityGroup.GroupId
      - !Ref VpcDefaultSG
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref AppOwner

Outputs:
  DBHOST:
    Value: !GetAtt DBServer.Endpoint.Address