Description: >
  Master Template ECS Full stack Load Balancer setup

Parameters:
  VpcId:
    Type: String

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

  SGIngressCidr: 
    Type: String
    Default: "0.0.0.0/0"

  SGIngressProtocol: 
    Type: String
    Default: "TCP"

  SGIngressFromPort:
    Type: Number
    Default: 80

  SGIngressToPort:
    Type: Number
    Default: 80

  LBListenerTGPort:
    Type: Number
    Default: 80

  LBHealthCheckProtocol:
    Type: String
    Default: HTTP

  Name: 
    Type: String

  Environment:
    Type: String

  AppOwner:
    Type: String

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub alb-${Name}
      SecurityGroupIngress:
        - CidrIp: !Ref SGIngressCidr
          IpProtocol: !Ref SGIngressProtocol
          FromPort: !Ref SGIngressFromPort
          ToPort: !Ref SGIngressToPort
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref AppOwner

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: !Ref Subnets
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref AppOwner

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: !Ref LBListenerTGPort
      Protocol: !Ref LBHealthCheckProtocol
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: LoadBalancer
    Properties:
      VpcId: !Ref VpcId
      Port: !Ref LBListenerTGPort
      Protocol: !Ref LBHealthCheckProtocol
      Matcher:
        HttpCode: 302
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /
      HealthCheckProtocol: !Ref LBHealthCheckProtocol
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30
        - Key: stickiness.enabled
          Value: true
        - Key: stickiness.lb_cookie.duration_seconds
          Value: 86400
        - Key: stickiness.type
          Value: lb_cookie
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref AppOwner

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref LoadBalancerListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
            - /
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward


Outputs:
  TargetGroup:
    Value: !Ref TargetGroup

  ServiceUrl:
    Description: URL of the load balancer for the sample service.
    Value: !Sub http://${LoadBalancer.DNSName}

  SecurityGroup:
    Value: !Ref SecurityGroup